apiVersion: v1 
kind: Pod 
metadata:
  labels:
    name: mysql-pod
  name: mysql-pod
  namespace: default 
spec:
  containers:
  - image: mysql
    imagePullPolicy: Always
    name: mysql
    envFrom:
    - secretRef:
        name: db-secret
