apiVersion: v1
kind: Service
metadata:
  name: httpd_pod
  labels:
    env  : prod
spec:
  selector:
    project: ek_httpd
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on the POD
  type: LoadBalancer
